name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main
      - add_windows_unittests

jobs:
  test:
    strategy:
      matrix:
        include:
        - os: "windows-latest"
          toolchain: "msvc"
          luaVersion: "5.1"
          neovim: "v0.10.0"
        - os: "windows-latest"
          toolchain: "mingw"  # unused, other than for display in the UI
          luaVersion: "luajit"
          neovim: "v0.10.0"

    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} ${{ matrix.toolchain }}, Lua ${{ matrix.luaVersion }}, Neovim: ${{ matrix.neovim }}"

    steps:
    - name: Setup MSVC
      # the 'hishamhm/gh-actions-lua' step requires msvc to build PuC Rio Lua
      # versions on Windows (LuaJIT will be build using MinGW/gcc).
      if: ${{ matrix.toolchain == 'msvc' }}
      uses: ilammy/msvc-dev-cmd@v1

    - uses: luarocks/gh-actions-lua@master
      with:
        luaVersion: "${{ matrix.luaVersion }}"

    - uses: luarocks/gh-actions-luarocks@v5

    - name: Install mega.logging
      run: |
        luarocks install mega.logging
        lua -e "require 'mega.logging'"

    - name: Install LuaFileSystem
      run: |
        luarocks install luafilesystem
        lua -e "require 'lfs'"